server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: crm-service
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
