server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: crm-service
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
        - id: inMateService
          uri: bl://inventory-service
          predicates:
            - Path=/inventory/**
